<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated;

use Automattic\WooCommerce\Internal\DependencyManagement\AbstractServiceProvider;

/**
 * Service provider for the API classes.
 */
class ApiClassesServiceProvider extends AbstractServiceProvider {
	// phpcs:disable Squiz.Commenting

	protected $provides = array(
		\Automattic\WooCommerce\Api\Foobars::class,
		\Automattic\WooCommerce\Api\Sandbox::class,
		\Automattic\WooCommerce\Api\Webhooks::class,
	);

	public function register() {
		foreach ( $this->provides as $class_name ) {
			$this->share( $class_name );
		}
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
