<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated;

use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use Automattic\WooCommerce\Internal\GraphQL\ApiException;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

/**
 * Root query type class for the GraphQL API.
 */
class RootQueryType extends ObjectType {

	// phpcs:disable Squiz.Commenting

	private $container;

	public function __construct() {
		$this->container = wc_get_container();

		$config = array(
			'name'        => 'Query',
			'description' => __( 'The query root of WooCommerce GraphQL API.', 'woocommerce' ),
			'fields'      => fn(): array => $this->get_fields(),
		);

		parent::__construct( $config );
	}

	private function get_fields() {
		return array_merge(
			GraphQLQueries\FoobarsQueries::get_queries(),
			GraphQLQueries\SandboxQueries::get_queries(),
			GraphQLQueries\WebhooksQueries::get_queries()
		);
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
