<?php

namespace Automattic\WooCommerce\Internal\Api\AutogeneratedMock\GraphQLQueries;

use Automattic\WooCommerce\Api\Webhooks;
use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

class WebhooksQueries {
	public static function get_queries(): array {
		$container = wc_get_container();

		return [
			'Webhooks' => array(
				'type'        => Type::listOf( Type::nonNull( GraphQLController::resolve_type( 'Webhook' ) ) ),
				'description' => 'Get webhooks!',
				'resolve'     => fn( $objectValue, array $args, $context, ResolveInfo $info) =>
					$container->get( Webhooks::class )->get_webhooks(),
			),
			'Webhook'  => array(
				'type'        => Type::nonNull( GraphQLController::resolve_type( 'Webhook' ) ),
				'description' => 'Get one webhook!',
				'args'        => array(
					'id' => array(
						'description' => 'Id of webhook to get.',
						'type'        => Type::nonNull( Type::int() ),
					),
				),
				'resolve'     => fn( $objectValue, array $args, $context, ResolveInfo $info) =>
					// $info->getFieldSelection(100)
					$container->get( Webhooks::class )->get_webhook( $args['id'], GraphQLController::get_fields_info( $info ) ),
			)
		];
	}
}
