<?php

namespace Automattic\WooCommerce\Internal\Api;

use Automattic\WooCommerce\Internal\Api\Autogenerated\RestControllersServiceProvider; //!!!AutogeneratedMock
use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use Automattic\WooCommerce\Utilities\StringUtil;

class Main {
	public static function initialize(): void {
        if(self::is_graphql_request()) {
            GraphQLController::initialize();
        }
	}

    public static function get_extra_service_providers(): array {
        if(self::is_rest_request()) {
            return [RestControllersServiceProvider::class];
        }
        else {
            return [];
        }
    }

    public static function is_graphql_request(): bool {
        return ($_SERVER['PATH_INFO'] ?? '') === '/wp-json/wc/v4/graphql';
    }

    public static function is_rest_request(): bool {
        return StringUtil::starts_with($_SERVER['PATH_INFO'] ?? '', '/wp-json/wc/v4/') && !self::is_graphql_request();
    }
}
