<?php

namespace Automattic\WooCommerce\Internal\Api\AutogeneratedMock;

use Automattic\WooCommerce\Internal\DependencyManagement\ServiceProviders\AbstractInterfaceServiceProvider;
use Automattic\WooCommerce\Internal\Api\AutogeneratedMock\RestControllers\WebhooksController;

class RestControllersServiceProvider extends AbstractInterfaceServiceProvider {

	/**
	 * The classes/interfaces that are serviced by this service provider.
	 *
	 * @var array
	 */
	protected $provides = array(
		WebhooksController::class,
	);

	/**
	 * Register the classes.
	 */
	public function register() {
		foreach ( $this->provides as $class_name ) {
			$this->share_with_implements_tags( $class_name );
		}
	}
}
