<?php

namespace Automattic\WooCommerce\Internal\Api\AutogeneratedMock;

use Automattic\WooCommerce\Api\InputTypes\CreateWebhookInput;
use Automattic\WooCommerce\Api\Webhooks;
use Automattic\WooCommerce\Internal\Api\AutogeneratedMock\GraphQLMutations\WebhooksMutations;
use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

class RootMutationType extends ObjectType {

	private $container;

	public function __construct() {
		$this->container = wc_get_container();

		$config = array(
			'name'        => 'Mutation',
			'description' => 'Base mutation type.',
			'fields'      => $this->get_fields(),
			/*
			'resolveField' => function( $value, $args, $context, ResolveInfo $info ) {
				return $this->resolve_field( $value, $args, $context, $info );
			},*/
		);

		parent::__construct( $config );
	}

	private function get_fields() {
		return array_merge(
			[],
			WebhooksMutations::get_mutations()
		);
	}

	private function resolve_field( $value, $args, $context, ResolveInfo $info ) {
		$resolver = $this->get_fields()[ $info->fieldName ]['resolve'] ?? null;

		if ( is_null( $resolver ) ) {
			throw new \Exception( "Unknown mutation: {$info->fieldName}" );
		}

		return $resolver( $value, $args, $context, $info );
	}
}
