<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL type for the CreateWebhookInput input type class.
 */
class CreateWebhookInputType extends \GraphQL\Type\Definition\InputObjectType {
	// phpcs:disable Squiz.Commenting

	public function __construct() {
		$config = array(
			'name'        => 'CreateWebhookInput',
			'description' => __( 'CreateWebhookInput input type', 'woocommerce' ),
			'fields'      => $this->get_fields(),
			'parseValue'  => fn( $values ) => GraphQLController::parse_input_value( 'CreateWebhookInput', $values ),
		);

		parent::__construct( $config );
	}

	public function get_fields() {
		$fields = array(
			'user_id' => fn() => array(
				'type' => Type::nonNull( Type::int() ),
			),
			'status'  => fn() => array(
				'type' => Type::nonNull( GraphQLController::resolve_type( 'WebhookStatus' ) ),
			),
		);
		$fields = array_merge( $fields, GraphQLController::resolve_type( 'WebhookDefinition' )->get_fields() );
		return $fields;
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
