<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL type for the IdentifiableObject interface class.
 */
class IdentifiableObjectType extends \GraphQL\Type\Definition\InterfaceType {
	// phpcs:disable Squiz.Commenting

	public function __construct() {
		$config = array(
			'name'        => 'IdentifiableObject',
			'description' => __( 'Represents an identifiable object.', 'woocommerce' ),
			'fields'      => $this->get_fields(),
			'resolveType' => function ( $value ) {
				return GraphQLController::resolve_type( get_class( $value ) );
			},
		);

		parent::__construct( $config );
	}

	public function get_fields() {
		return array(
			'id'   => fn() => array(
				'type'        => Type::int(),
				'description' => __( 'Object id', 'woocommerce' ),
			),
			'name' => fn() => array(
				'type' => Type::string(),
			),
		);
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
