<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

/**
 * GraphQL type for the MsxGeneration enum type class.
 */
class MsxGenerationType extends \GraphQL\Type\Definition\EnumType {
	// phpcs:disable Squiz.Commenting

	public function __construct() {
		$config = array(
			'name'        => 'MsxGeneration',
			'description' => __( 'Generation of MSX computer.', 'woocommerce' ),
			'values'      => array(
				'MSX1'     => array(
					'value'       => 'MSX',
					'description' => __( 'Original MSX', 'woocommerce' ),
				),
				'MSX2'     => array(
					'value' => 'MSX2',
				),
				'MSX2PLUS' => array(
					'value' => 'MSX2+',
				),
				'MSXTR'    => array(
					'value' => 'MSX Turbo-R',
				),
			),
		);

		parent::__construct( $config );
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
