<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL type for the Thing input type class.
 */
class ThingType extends \GraphQL\Type\Definition\InputObjectType {
	// phpcs:disable Squiz.Commenting

	public function __construct() {
		$config = array(
			'name'        => 'Thing',
			'description' => __( 'Thing input type', 'woocommerce' ),
			'fields'      => $this->get_fields(),
			'parseValue'  => fn( $values ) => GraphQLController::parse_input_value( 'Thing', $values ),
		);

		parent::__construct( $config );
	}

	public function get_fields() {
		$fields = array(
			'id'   => fn() => array(
				'type' => Type::nonNull( Type::int() ),
			),
			'name' => fn() => array(
				'type' => Type::nonNull( Type::string() ),
			),
		);

		return $fields;
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
