<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

/**
 * GraphQL type for the WebhookStatus enum type class.
 */
class WebhookStatusType extends \GraphQL\Type\Definition\EnumType {
	// phpcs:disable Squiz.Commenting

	public function __construct() {
		$config = array(
			'name'        => 'WebhookStatus',
			'description' => __( 'WebhookStatus enum type', 'woocommerce' ),
			'values'      => array(
				'ACTIVE'   => array(
					'value' => 'active',
				),
				'PAUSED'   => array(
					'value' => 'paused',
				),
				'DISABLED' => array(
					'value' => 'disabled',
				),
			),
		);

		parent::__construct( $config );
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
