<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

/**
 * GraphQL type for the WebhookApiType enum type class.
 */
class WebhookApiTypeType extends \GraphQL\Type\Definition\EnumType {
	// phpcs:disable Squiz.Commenting

	public function __construct() {
		$config = array(
			'name'        => 'WebhookApiType',
			'description' => __( 'Webhook API type enum!', 'woocommerce' ),
			'values'      => array(
				'API_V1'    => array(
					'value'       => 'wp_api_v1',
					'description' => __( 'API v1 payload', 'woocommerce' ),
				),
				'API_V2'    => array(
					'value'       => 'wp_api_v2',
					'description' => __( "You don\'t say!!", 'woocommerce' ),
				),
				'API_V3'    => array(
					'value' => 'wp_api_v3',
				),
				'LEGACY_V3' => array(
					'value'       => 'legacy_v3',
					'description' => __( 'Legacy API v3 payload', 'woocommerce' ),
				),
				'FOO'       => array(
					'value' => 34,
				),
			),
		);

		parent::__construct( $config );
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
