<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL type for the WebhookDefinition interface class.
 */
class WebhookDefinitionType extends \GraphQL\Type\Definition\InterfaceType {
	// phpcs:disable Squiz.Commenting

	public function __construct() {
		$config = array(
			'name'        => 'WebhookDefinition',
			'description' => __( 'Represents a webhook definition.', 'woocommerce' ),
			'fields'      => $this->get_fields(),
			'resolveType' => function ( $value ) {
				return GraphQLController::resolve_type( get_class( $value ) );
			},
		);

		parent::__construct( $config );
	}

	public function get_fields() {
		return array(
			'name'         => fn() => array(
				'type' => Type::nonNull( Type::string() ),
			),
			'topic'        => fn() => array(
				'type'        => Type::nonNull( Type::string() ),
				'description' => __( 'The topic of the webhook.', 'woocommerce' ),
			),
			'delivery_url' => fn() => array(
				'type' => Type::nonNull( Type::string() ),
			),
			'secret'       => fn() => array(
				'type' => Type::string(),
			),
			'api_version'  => fn() => array(
				'type' => Type::nonNull( GraphQLController::resolve_type( 'WebhookApiType' ) ),
			),
		);
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
