<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLQueries;

use \Automattic\WooCommerce\Api\Foobars;
use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL queries for the Foobars API class.
 */
class FoobarsQueries {
	// phpcs:disable Squiz.Commenting

	public static function get_queries(): array {
		$container = wc_get_container();

		return array(
			'Fizz' => array(
				'type'        => Type::nonNull( GraphQLController::resolve_type( 'AnInt' ) ),
				'description' => __( 'Fizz query type', 'woocommerce' ),
				'args'        => array(),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Foobars::class )->fizz(),
			),
		);
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
