<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLQueries;

use \Automattic\WooCommerce\Api\Sandbox;
use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL queries for the Sandbox API class.
 */
class SandboxQueries {
	// phpcs:disable Squiz.Commenting

	public static function get_queries(): array {
		$container = wc_get_container();

		return array(
			'RandomSimpleType'    => array(
				'type'        => Type::nonNull( GraphQLController::resolve_type( 'SimpleType' ) ),
				'description' => __( 'Get an instance of SimpleType with random(ish)values.', 'woocommerce' ),
				'args'        => array(),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Sandbox::class )->get_random_simple_type(),
			),
			'RandomSimpleTypes'   => array(
				'type'        => Type::nonNull( Type::listOf( Type::NonNull( GraphQLController::resolve_type( 'SimpleType' ) ) ) ),
				'description' => __( 'Get a few instances of SimpleType with random(ish)values.', 'woocommerce' ),
				'args'        => array(
					'how_many' => array(
						'description' => __( 'How many instances to get?', 'woocommerce' ),
						'type'        => Type::int(),
					),
				),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Sandbox::class )->get_random_simple_types( $args['how_many'] ?? null ),
			),
			'PopulatedSimpleType' => array(
				'type'        => Type::nonNull( GraphQLController::resolve_type( 'SimpleType' ) ),
				'description' => __( 'Get an instance of SimpleType with values populated from the input.', 'woocommerce' ),
				'args'        => array(
					'input' => array(
						'type' => Type::nonNull( GraphQLController::resolve_type( 'GetPopulatedSimpleTypeInput' ) ),
					),
				),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Sandbox::class )->get_populated_simple_type( $args['input'] ),
			),
			'ComplexType'         => array(
				'type'        => Type::nonNull( GraphQLController::resolve_type( 'ComplexType' ) ),
				'description' => __( 'Get an instance of ComplexType with random(ish)values.', 'woocommerce' ),
				'args'        => array(),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Sandbox::class )->get_random_complex_type(),
			),
			'IdentifiableObjects' => array(
				'type'        => Type::nonNull( Type::listOf( Type::NonNull( GraphQLController::resolve_type( 'IdentifiableObject' ) ) ) ),
				'description' => __( 'IdentifiableObjects query type', 'woocommerce' ),
				'args'        => array(),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Sandbox::class )->get_identifiable_objects(),
			),
		);
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
