<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLQueries;

use \Automattic\WooCommerce\Api\Webhooks;
use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL queries for the Webhooks API class.
 */
class WebhooksQueries {
	// phpcs:disable Squiz.Commenting

	public static function get_queries(): array {
		$container = wc_get_container();

		return array(
			'GetInts'     => array(
				'type'        => Type::nonNull( Type::listOf( Type::NonNull( GraphQLController::resolve_type( 'AnInt' ) ) ) ),
				'description' => __( 'GetInts query type', 'woocommerce' ),
				'args'        => array(
					'ints' => array(
						'description' => __( 'The ints to return.', 'woocommerce' ),
						'type'        => Type::nonNull( Type::listOf( Type::NonNull( Type::int() ) ) ),
					),
				),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Webhooks::class )->get_ints( $args['ints'] ),
			),
			'GetInt'      => array(
				'type'        => Type::nonNull( GraphQLController::resolve_type( 'AnInt' ) ),
				'description' => __( 'GetInt query type', 'woocommerce' ),
				'args'        => array(
					'int' => array(
						'description' => __( 'The int to return.', 'woocommerce' ),
						'type'        => Type::nonNull( Type::int() ),
					),
				),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Webhooks::class )->get_int( $args['int'] ),
			),
			'Webhooks'    => array(
				'type'        => Type::nonNull( Type::listOf( Type::NonNull( GraphQLController::resolve_type( 'Webhook' ) ) ) ),
				'description' => __( 'Go and get webhooks!', 'woocommerce' ),
				'args'        => array(),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Webhooks::class )->get_webhooks(),
			),
			'EchoWebhook' => array(
				'type'        => Type::nonNull( GraphQLController::resolve_type( 'Webhook' ) ),
				'description' => __( 'EchoWebhook query type', 'woocommerce' ),
				'args'        => array(
					'input' => array(
						'type' => Type::nonNull( GraphQLController::resolve_type( 'CreateWebhookInput' ) ),
					),
				),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Webhooks::class )->echo_webhooks( $args['input'] ),
			),
			'Webhook'     => array(
				'type'        => GraphQLController::resolve_type( 'Webhook' ),
				'description' => __( 'Webhook query type', 'woocommerce' ),
				'args'        => array(
					'id' => array(
						'description' => __( 'The id, that is', 'woocommerce' ),
						'type'        => Type::nonNull( Type::int() ),
					),
				),
				'resolve'     => fn( $object_value, array $args, $context, ResolveInfo $info) => $container->get( Webhooks::class )->get_webhook( $args['id'], GraphQLController::get_fields_info( $info ) ),
			),
		);
	}

	// phpcs:enable Squiz.Commenting
}

// Autogenerated file, don't modify manually!
