<?php

namespace Automattic\WooCommerce\Internal\Api\AutogeneratedMock\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;

class CreateWebhookInputType extends InputObjectType {
	public function __construct() {
		$config = array(
			'name'        => 'CreateWebhookInput',
			'description' => __( 'Data for a new webhook.', 'woocommerce' ),
			'fields'      => $this->get_fields(),
			'interfaces'  => array(
				GraphQLController::resolve_type( 'WebhookDefinition' ),
			),
			'parseValue'  => fn( $values) => GraphQLController::parse_input_value( 'CreateWebhookInput', $values ),
		);

		parent::__construct( $config );
	}
	private function get_fields() {
		$fields = array(
			'user_id' => fn() => array(
				'description' => 'Webhook user id.',
				'type'        => Type::nonNull( Type::int() ),
			),
			'status'  => fn() => array(
				'description' => 'Webhook status.',
				'type'        => Type::nonNull( GraphQLController::resolve_type( 'WebhookStatus' ) ),
			),
		);

		$fields = array_merge( $fields, GraphQLController::resolve_type( 'WebhookDefinition' )->get_fields() );

		return $fields;
	}

	public static function parse( array $input_value ) {
		// TODO: support for properties being arrays and other objects
		return GraphQLController::parse_input_value( 'CreateWebhookInput', $input_value );
	}
}
