<?php

namespace Automattic\WooCommerce\Internal\Api\AutogeneratedMock\GraphQLTypes;

use GraphQL\Type\Definition\EnumType;

class WebhookStatusType extends EnumType {
	public function __construct() {
		$config = array(
			'name'        => 'WebhookStatus',
			'description' => 'Webhook status.',
			'values'      => array(
				'ACTIVE'   => array(
					'value' => 'active',
				),
				'PAUSED'   => array(
					'value' => 'paused',
				),
				'DISABLED' => array(
					'value' => 'disabled',
				),
			),
		);

		parent::__construct( $config );
	}
}
