<?php

namespace Automattic\WooCommerce\Internal\Api\AutogeneratedMock\GraphQLTypes;

use GraphQL\Type\Definition\EnumType;

class WebhookApiVersionType extends EnumType {
	public function __construct() {
		$config = array(
			'name'        => 'WebhookApiType',
			'description' => 'Webhook API type.',
			'values'      => array(
				'API_V1'    => array(
					'value' => 'wp_api_v1',
				),
				'API_V2'    => array(
					'value' => 'wp_api_v2',
				),
				'API_V3'    => array(
					'value' => 'wp_api_v4',
				),
				'LEGACY_V3' => array(
					'value' => 'legacy_v3',
				),
			),
		);

		parent::__construct( $config );
	}
}
